<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Appeal Text' => 'Описание обращения',
    'Channel' => 'Канал',
    'City ID' => 'Город',
    'Complaint Object' => 'Жалоба на сотрудника Компании',
    'Count Problem' => 'В который раз у клиента возникает проблема?',
    'Count Request' => 'В который раз клиент обращается с жалобой?',
    'Customer ID' => 'Клиент',
    'Delivery Late' => 'На сколько часов заказ опоздала доставка?',
    'Language' => 'На каком языке клиент разговаривает?',
    'Name' => 'Клиент',
    'Order Number' => 'Номер заказа в СРМ',
    'Phone' => 'Номер телефона',
    'Rating' => 'Оценка',
    'Select channel' => 'Выберите канал',
    'Type' => 'Тип',
];
