<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CATEGORY_CARE' => 'Служба поддержки',
    'CATEGORY_CERTIFICATE' => 'Сертификат',
    'CATEGORY_DELIVERY' => 'Доставка',
    'CATEGORY_KASPI' => 'Kaspi',
    'CATEGORY_MOBILE' => 'Меломан приложение',
    'CATEGORY_PRODUCT' => 'Продукция',
    'CATEGORY_SITE' => 'Сайт Марвин Меломан',
    'CATEGORY_STORE' => 'Торговая точка',
    'COMPLAINT_OBJECT_1' => 'Невнимательность',
    'COMPLAINT_OBJECT_2' => 'Безразличие',
    'COMPLAINT_OBJECT_3' => 'Грубость/Мошенничество',
    'COMPLAINT_OBJECT_4' => 'Клиент не жалуется на сотрудника Компании',
    'COMPLAINT_VALIDITY_NO' => 'Не обосновано',
    'COMPLAINT_VALIDITY_YES' => 'Обосновано',
    'COUNT_PROBLEM_1' => 'Первый',
    'COUNT_PROBLEM_2' => 'Второй',
    'COUNT_PROBLEM_3' => 'Третий и более',
    'COUNT_REQUEST_1' => 'Первый',
    'COUNT_REQUEST_2' => 'Второй',
    'COUNT_REQUEST_3' => 'Третий и более',
    'Care Text' => 'Текст обращении',
    'Category' => 'Категория',
    'Channel' => 'Канал',
    'City ID' => 'Город',
    'Compensation' => 'Компенсация',
    'Complaint Object' => 'Жалоба на сотрудника Компании',
    'Complaint Personal' => 'ФИО сотрудника',
    'Complaint Reason' => 'Причина претензии',
    'Complaint Validity' => 'Обоснованность',
    'Completed At' => 'Дата завершения',
    'Count Problem' => 'В который раз у клиента возникает проблема?',
    'Count Request' => 'В который раз клиент обращается с жалобой?',
    'Created At' => 'Дата создания',
    'Created By' => 'Автор',
    'Customer ID' => 'Клиент',
    'DELIVERY_LATE_1' => 'до 1 часа',
    'DELIVERY_LATE_2' => 'от 1 до 2-х часов',
    'DELIVERY_LATE_3' => 'от 2-х часов и более',
    'DELIVERY_LATE_4' => 'Клиент не жалуется на время доставки',
    'Delivery Late' => 'Опоздание доставки',
    'Executor ID' => 'Переведенный оператор',
    'Extra Fields' => 'Дополнительные поля',
    'FINAL_STATUS_DELETED' => 'Отзыв удален',
    'FINAL_STATUS_NO_CHANGES' => 'Без изменений',
    'FINAL_STATUS_POSITIVE' => 'Изменил на положительный',
    'Final Status' => 'Статус после обработки',
    'Handler ID' => 'Оператор',
    'ID' => 'ИД',
    'Language' => 'На каком языке клиент разговаривает?',
    'Name' => 'Имя клиента',
    'Number' => 'Номер обращении',
    'Order Number' => 'Номер заказа',
    'Phone' => 'Номер телефона',
    'Rating' => 'Оценка',
    'Solution Measures' => 'Принятые меры',
    'Solution Text' => 'Решение',
    'Status' => 'Статус',
    'Store Number' => 'Наименование точки',
    'TYPE_TRANSFER' => 'Передача',
    'Type' => 'Тип',
];
