<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CHANNEL_CRM' => 'CRM',
    'CHANNEL_JIVOSITE_INSTAGRAM' => 'Jivo: Instagram',
    'CHANNEL_JIVOSITE_SITE' => 'Jivo: Сайт',
    'CHANNEL_JIVOSITE_WHATSAPP' => 'Jivo: Whatsapp',
    'STATUS_CANCELLED' => 'Отказ',
    'STATUS_CLOSED' => 'Закрытый запрос',
    'STATUS_CREATED' => 'Создан',
    'STATUS_NEW' => 'Новый',
    'STATUS_PENDING' => 'Отложен',
    'STATUS_PROCESS' => 'В обработке',
    'STATUS_SUCCESS_B2B' => 'Завершенный оптовый лид',
    'STATUS_SUCCESS_B2C' => 'Завершенный розничный лид',
    'TYPE_CARE_CREATED' => 'Создано обращение на основании этого лида',
    'TYPE_JIVOSITE_CLIENT_UPDATED' => 'Клиент Jivosite обновлен',
    'TYPE_JIVOSITE_CREATED' => 'Диалог Jivosite создан',
    'TYPE_JIVOSITE_FINISHED' => 'Диалог Jivosite завершен',
    'TYPE_ORDER_CREATED' => 'Создан заказ на основании этого лида',
    'TYPE_TRANSFER' => 'Передача',
];
