<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account ozon' => 'Аккаунт Ozon',
    'Account wb' => 'Аккаунт Wildberries',
    'Assembly is not allowed in this status' => 'Сборка не доступна на данном статусе',
    'Courier Name' => 'ФИО курьера',
    'Courier Phone' => 'Номер телефона курьера',
    'Delivery Method' => 'Способ доставки',
    'Event' => 'Событие',
    'Handler ID' => 'Обработал',
    'Incorrect quantity {product}, required: {required}, current: {current}' => 'Некорректная сборка товара: {product}, нужно: {required}, собрано: {current}',
    'Order cannot be edited in this status.' => 'Заказ нельзя редактировать в этом статусе',
    'Order has no payment.' => 'Оплата по заказу не найдена',
    'Order store status not assembled' => 'Точка продажи не подтвердила сборку',
    'Payment Method' => 'Способ оплаты',
    'Payment №{number}' => 'Оплата №{number}',
    'Product not found' => 'Товар не найден',
    'Receipt return' => 'Чек возврата',
    'Receipt sale' => 'Чек продажи',
    'Sku' => 'SKU',
    'Store ID' => 'Точка продажи',
    'TYPE_TRANSFER' => 'Передача',
    'The order amount exceeds the payment amount to {cost}' => 'Сумма заказа превышает сумму платежа на {cost}',
    'This channel is not allowed to add products' => 'В этом канале запрещено добавлять товары',
    'This channel is not allowed to delete products' => 'В этом канале запрещено удалять товары',
    'This channel is not allowed to edit products' => 'В этом канале запрещено редактировать товары',
    'This order cannot be added product.' => 'В этот заказ нельзя добавлять товар.',
    'Transferred' => 'Был передан',
    'Vendor ID' => 'ID канала',
    'Vendor Number' => 'Номер канала',
    'You cant edit while assembled, you must first delete the build' => 'Нельзя редактировать при сборки, сначала удалить сборку',
];
