<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created At' => 'Дата создания',
    'Email' => 'Почта',
    'Full Name' => 'ФИО',
    'ID' => 'ИД',
    'Password' => 'Пароль',
    'Password Repeat' => 'Повторите пароль',
    'Password must contain at least one lower and upper case character and a digit.' => 'Пароль должен состоять с большой буквой, с маленькой буквой и с цифрами',
    'Phone' => 'Номер телефона',
    'Role' => 'Роль',
    'State' => 'Смена',
    'Status' => 'Статус',
    'Telegram Id' => 'Telegram ИД',
];
